spring:
  application:
    name: bakery

  datasource:
    url: jdbc:postgresql://localhost:5432/bakery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.somi.bakery: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always